apiVersion: v1
kind: ConfigMap
metadata:
  name: v-code-config
data:
  PORT: "3001"
  AZURE_STORAGE_CONTAINER_NAME: "codex-bucket"
  AZURE_STORAGE_ACCOUNT_NAME: "tusharblobstore"
  # Updated with your LoadBalancer IP
  CLIENT_ORIGINS: "http://20.204.187.189,https://20.204.187.189,http://localhost:5173"
  COPY_DIST: "./../../../../s3-code"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  # Updated with your LoadBalancer IP
  FRONTEND_URL: "http://20.204.187.189"
  BACKEND_URL: "http://20.204.187.189"